_ENDPOINT_CONTROL_HANIME1_SEEDS = '/api/v1/control/runtime/hanime1/seeds'
_ENDPOINT_CONTROL_JOBS = '/api/v1/control/jobs'
_ENDPOINT_CONTROL_REQUESTS = '/api/v1/control/requests'
_ENDPOINT_HEALTH = '/api/v1/health'
_ENDPOINT_NOTIFICATIONS = '/api/v1/notifications'
_ENDPOINT_NOTIFICATIONS_ACK = '/api/v1/notifications/ack'
_ENDPOINT_RUNTIME_HANIME1_DOWNLOADED_IDS = '/api/v1/runtime/hanime1/downloaded-ids'
_CACHE_CONTROL = 'private, max-age=60'
_CONTENT_TYPE_JSON = 'application/json; charset=utf-8'
_AUTH_PREFIX = 'Bearer '
_DEFAULT_BIND = '127.0.0.1'
_DEFAULT_PORT = 8091
_HEADER_AUTHORIZATION = 'authorization'
_HEADER_IF_NONE_MATCH = 'if-none-match'
_HEADER_CONTENT_TYPE = 'Content-Type'
_HEADER_CACHE_CONTROL = 'Cache-Control'
_HEADER_WWW_AUTHENTICATE = 'WWW-Authenticate'
_HEADER_ETAG = 'ETag'
_HEADER_ALLOW = 'Allow'
_HEADER_CONTENT_LENGTH = 'Content-Length'
_MAX_PORT = 65535
